### ISSUE TITLE
Arrumar upload de imagem da organização e de perfil

### ISSUE THREAD

**Issue by renatasoares** [gestorpsi-mes-12017/gestorpsi#8]
Não é possível mudar ou fazer o upload da imagem da organização

**Comment by mateusmanuel** [comment]
Foi identificado o problema que ocasionava o erro. 

A alteração foi submetida no PR[#118](https://github.com/caep-unb/gestorpsi/pull/118) para o repositório do CAEP.

Ele foi aceito, logo o _issue_ está sendo fechada.
